//----------------------------------------------------------------------------------------------------
// <auto-generated>
//     Generated by the protoc-gen-csa tool.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------------------

using Google.Protobuf;

namespace CsaCommon;

public interface IModelable<T>
{
    T ToModel(string? propertyPath = null);
}

public interface IMessageable<T> where T : IMessage<T>
{
    T ToMessage();
}
